security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    # Définir comment on récupere les users 
    providers:
        from_database:
            entity:
                class: App\Entity\User
                property: username

    # Définir les composants qui écoutent les requetes et effectuent des actions particulières
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # Chaque personne qui entre est considérée comme anonyme
            anonymous: true
            logout:
               path: /logout
               target: / 

            # activate different ways to authenticate
            # http_basic: true
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            form_login:
                check_path: login
            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Savoir qui a accès à quoi
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

    # définir les encodeurs pour les differentes classes
    encoders:
        # On définit la sécurité à apporter
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        
