twig:
    # Les templates sont à charger ici
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    #type de theme à utiliser pour les formulaires
    form_themes: ['bootstrap_4_layout.html.twig']
